[[redirects]]
  from = "/home"
  to = "https://go.advisorlaunch.com/version-test/home"
  status = 200
  force = true
  
  
[[redirects]]
  from = "/home"
  to = "https://go.advisorlaunch.com/version-test/:splat"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
