[[redirects]]
  from = "/*"
  to = "https://go.advisorlaunch.com/version-test/index"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
