[[redirects]]
  from = "/index"
  to = "https://go.advisorlaunch.com/version-test/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", X-From = "Netlify"}

[[redirects]]
  from = "/version-test/elasticsearch/mget"
  to = "https://go.advisorlaunch.com/version-test/elasticsearch/mget"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", X-From = "Netlify"}
