[[redirects]]
  from = "/*"
  to = "https://go.advisorlaunch.com/version-test/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


[[redirects]]
  from = "/*"
  to = "https://go.advisorlaunch.com/version-test/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
