[[redirects]]
  from = "/index/*"
  to = "https://go.advisorlaunch.com/version-test/index/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}


[[redirects]]
  from = "/home/*"
  to = "https://go.advisorlaunch.com/version-test/home/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}
