[[redirects]]
  from = "/index/*"
  to = "https://go.advisorlaunch.com/version-test/index"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/workflow/*"
  to = "https://go.advisorlaunch.com/workflow/:splat"
  status = 200
    force = true
  headers = {Access-Control-Allow-Origin = "*"}
